export declare const ROUTE_DECISION_REFRESH_TASK_TYPE = "route-decision.refresh";
export type RouteMode = 'pattern' | 'explicit_group';
export type RouteDecisionCandidate = {
    channelId: number;
    accountId: number;
    username: string;
    siteName: string;
    tokenName: string;
    priority: number;
    sortOrder: number;
    weight: number;
    eligible: boolean;
    recentlyFailed: boolean;
    avoidedByRecentFailure: boolean;
    failureCount?: number;
    consecutiveFailureCount?: number;
    cooldownUntil?: string | null;
    observationPool?: 'primary' | 'observation' | null;
    observationRemainingRequests?: number | null;
    observationDueNow?: boolean;
    observationBlockedByCooldown?: boolean;
    stickyMode?: 'none' | 'session' | 'route_unit';
    stickyHit?: boolean;
    stickyBindingCount?: number;
    probability: number;
    reason: string;
};
export type RouteDecision = {
    requestedModel: string;
    actualModel: string;
    matched: boolean;
    selectedChannelId?: number;
    selectedLabel?: string;
    summary: string[];
    candidates: RouteDecisionCandidate[];
};
export declare function normalizeTokenRouteMode(routeMode: unknown): RouteMode;
